language: java

jdk:
  - oraclejdk8

os:
  - linux

before_install:
  - git clone --depth=1 https://github.com/wenerme/bbvm-test.git

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$REPO_TOKEN
